# Generated by Django 4.2.7 on 2023-11-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
